## Fixed-Type Arrays 

In [2]:
import array
L = list(range(10))
# integer array
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
A + 3

TypeError: can only append array (not "int") to array

In [2]:
array.array('f', L)

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

## Numpy Arrays

In [5]:
import numpy as np

B = np.array([1, 4, 2, 5, 3])
B

array([1, 4, 2, 5, 3])

In [6]:
B + 3

array([4, 7, 5, 8, 6])

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
# type 지정
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
# 다차원 array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Generator

In [7]:
# 모든 요소가 0인 array
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# 모든 요소가 1인 3x5 array
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# 모든 요소가 3.14인 3x5 array
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0, 20, 2)  # np.array(range(0, 20, 2))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# 균등 분포
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# random
np.random.random((3, 3))

array([[0.81033962, 0.18176729, 0.15375964],
       [0.59617766, 0.23765498, 0.05812001],
       [0.47508986, 0.25124647, 0.67619161]])

In [13]:
# normally distributed random values
np.random.normal(0, 1, (3, 3))

array([[ 0.1363336 ,  0.27049694, -0.55273595],
       [ 0.40151595,  1.0692871 , -1.21519165],
       [ 1.38866456,  1.01967541,  0.01856535]])

In [14]:
np.random.randint(0, 10, (3, 3))

array([[6, 6, 3],
       [6, 4, 4],
       [2, 3, 9]])

In [15]:
# 대각 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.empty(3)

array([1., 1., 1.])

## Data Types

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

## Attributes

In [5]:
# 3차원 array 생성
import numpy as np
np.random.seed(0)  
x3 = np.random.randint(10, size=(3, 4, 5))  
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [7]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
x3.ndim
x3.shape
x3.size

3

(3, 4, 5)

60

In [20]:
x3.dtype

dtype('int64')

In [21]:
# 요소 크기, 전체 크기
x3.itemsize
x3.nbytes # itemsize x size

8

480

## Indexing

#### - access single

In [22]:
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [23]:
x3[0]

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

In [24]:
x3[0][1]

array([9, 3, 5, 2, 4])

In [25]:
x3[0][1][2]

5

In [26]:
x3[-1]

array([[9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6],
       [8, 4, 1, 4, 9]])

In [27]:
x3[0, 1, 2] = 100
x3

array([[[  5,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

In [28]:
# auto type casting
x3[0, 1, 2] = 100.34
x3

array([[[  5,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

#### - Access Subarrays

``` python
x[start:stop:step]
x[start::step]
```

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:5]  

array([0, 1, 2, 3, 4])

In [31]:
x[5:]  

array([5, 6, 7, 8, 9])

In [32]:
x[4:7]  

array([4, 5, 6])

In [33]:
x[::2]  
x[1::2]
x[3::-1]
x[::-1]

array([0, 2, 4, 6, 8])

array([1, 3, 5, 7, 9])

array([3, 2, 1, 0])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
x3[:1, :2, :1]

array([[[5],
        [9]]])

In [35]:
x3[::-1, ::-1, ::-1]

array([[[  9,   4,   1,   4,   8],
        [  6,   5,   5,   4,   0],
        [  0,   2,   7,   2,   3],
        [  7,   4,   0,   9,   9]],

       [[  1,   0,   7,   3,   3],
        [  3,   1,   8,   3,   2],
        [  0,   5,   3,   0,   3],
        [  4,   9,   8,   9,   5]],

       [[  1,   8,   7,   7,   6],
        [  1,   8,   8,   6,   7],
        [  4,   2, 100,   3,   9],
        [  7,   3,   3,   0,   5]]])

In [36]:
x3[:, 0, 0]

array([5, 5, 9])

### Subarrays 의 반환값은 ``view``


In [37]:
sub = x3[0, :, :]
sub

array([[  5,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [38]:
sub[0, 0] = 300
sub

array([[300,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [39]:
# x3도 변경됨
x3

array([[[300,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

## array copy

In [40]:
sub = x3[0, :, :].copy()
sub

array([[300,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [41]:
sub[0, 0] = 900
sub

array([[900,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [42]:
# x3는 그대로
x3

array([[[300,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

## Reshaping

In [9]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
x = np.array([1, 2, 3])
x
y = x.reshape((1, 3))
y

array([1, 2, 3])

array([[1, 2, 3]])

In [11]:
x.ndim
x.shape
y.ndim
y.shape

1

(3,)

2

(1, 3)

In [12]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [13]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [14]:
y[np.newaxis, :]

array([[[1, 2, 3]]])

In [49]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

## Array Concatenation

In [50]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [51]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [52]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [53]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [56]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [57]:
# 크기가 다르면 error 
np.vstack([y, grid])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 3

## Splitting of arrays


```ipython
np.split(arr, integer) # integer 등분
np.split(arr, 1-D array) # 구간 [n, m] : 0 ~ n-1, n ~ m - 1, m ~ len(arr)  ( index 기준 ) 
```

In [15]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [16]:
np.split(x, [5, 1])

[array([ 1,  2,  3, 99, 99]),
 array([], dtype=int64),
 array([ 2,  3, 99, 99,  3,  2,  1])]

In [61]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
upper, lower = np.vsplit(grid, [2])
upper
lower

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
left, right = np.hsplit(grid, [2])
left
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])