## - array의 값으로 1을 나누는 계산 

## loop를 사용한 계산

In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

## UFuncs : *vectorized* operation

In [3]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


### 1. 속도 비교

In [4]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)
%timeit (1.0 / big_array)

1.99 s ± 9.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.67 ms ± 20 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [6]:
# 2-D Array
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### 2. 산술 연산

In [7]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) 
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [8]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [9]:
np.add(x, 2)

array([2, 3, 4, 5])

#### - wrapper

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

### 3. Absolute value

In [16]:
# python 내장 함수
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [10]:
# numpy 함수
np.absolute(x) #  np.abs(x)

array([0, 1, 2, 3])

In [11]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### 4. 삼각 함수

In [12]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [13]:
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
# 역삼각 함수
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### 5. Exp, Log

In [15]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [16]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


## Advanced Ufunc Features

### 1. Specifying output

In [17]:
x = np.arange(5)
y = np.empty(5)
z = np.multiply(x, 10)
z

array([ 0, 10, 20, 30, 40])

In [18]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=z) # output 지정
z

array([ 0, 10, 20, 30, 40])

In [19]:
# 크기가 다름 
y = np.zeros(10)
np.power(2, x, out=y)
y

ValueError: operands could not be broadcast together with shapes () (5,) (10,) 

In [27]:
y = np.zeros(10)
np.power(2, x, out=y[::2])  # y[::2] : step 2
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

### 2. Outer products

a = [a0, a1, ..., aM] , b = [b0, b1, ..., bN]

```
 [[a0*b0  a0*b1 ... a0*bN ]
 [a1*b0    .
 [ ...          .
 [aM*b0            aM*bN ]]
```


In [35]:
x = np.arange(1, 6)
np.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

## Aggregations

### 1. Sum

In [36]:
# python 내장함수
L = np.random.random(100)
sum(L)

50.461758453195614

In [37]:
# numpy 함수
np.sum(L) 

50.46175845319564

In [38]:
# 속도 비교
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

122 ms ± 2.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
304 µs ± 4.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 2. Min, Max

In [39]:
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [40]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [41]:
big_array.min(), big_array.max(), big_array.sum()

(7.071203171893359e-07, 0.9999997207656334, 500216.8034810001)

In [42]:
%timeit min(big_array)
%timeit np.min(big_array)
%timeit big_array.min()

77.4 ms ± 327 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
370 µs ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
364 µs ± 16.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 3. Multi dimensional aggregates

In [4]:
M = np.random.random((3, 4))
M

array([[0.94478189, 0.941399  , 0.80130499, 0.44451464],
       [0.35076285, 0.90142824, 0.71426303, 0.15288191],
       [0.11541516, 0.49267892, 0.94417819, 0.23536865]])

In [44]:
M.sum()

5.1136763453287335

In [45]:
# column 중에서 min
M.min(axis=0)

array([0.18441813, 0.11936151, 0.37497044, 0.03193135])

In [5]:
import numpy as np
?M.min

Docstring:
a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)

Return the minimum along a given axis.

Refer to `numpy.amin` for full documentation.

See Also
--------
numpy.amin : equivalent function
Type:      builtin_function_or_method


In [46]:
# row 중에서 min
M.min(axis=1)

array([0.03193135, 0.11957117, 0.11936151])

### 4. Other aggregation functions

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

### 5. reduce, accumulate

In [47]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [49]:
np.multiply.reduce(x)

120

In [50]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [51]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

## Broadcasting

#### - 크기가 다른 array간의 연산

In [52]:
a = np.array([0, 1, 2])
a + 5

array([5, 6, 7])

In [53]:
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [54]:
b = np.array([5])
a + b

array([5, 6, 7])

In [55]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
M + a # shape 자동 변환

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [57]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [58]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 1. Concept

<img src='broadcasting.png'>broadcasting</img>

### 2. Rules

 1. 두 array의 차원 수가 다른 경우 더 적은 차원을 가진 배열의 모양이 앞쪽 (왼쪽)에 채워 짐
 2. 두 array의 모양이 어떤 차원에서도 일치하지 않으면 해당 차원에서 모양이 1 인 배열은 다른 모양과 일치하도록 늘어 남
 3. 어떤 차원에서든 크기가 일치하지 않고 1과 같지 않으면 오류가 발생

### 3. example 1

In [59]:
M = np.ones((2, 3))
a = np.arange(3)
print(M.shape)
print(a.shape)

(2, 3)
(3,)


In [60]:
print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

rule 1 >>>

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

rule 2 >>> 

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

broadcasting **a** :  ``(2, 3)``:

`` [[0, 1, 2]
  [0, 1, 2]]``

In [61]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

### 4. example 2

In [62]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 >>>

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

rule 2 >>>

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

broadcasting **a** :

``[[0, 0, 0]
 [1, 1, 1]
 [2, 2, 2]]``

broadcasting **b** :

``[[0, 1, 2]
 [0, 1, 2]
 [0, 1, 2]]``

In [63]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 5. example 3

In [64]:
M = np.ones((3, 2))
a = np.arange(3)
print(M)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

rule 1 >>>

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

rule 2 >>>

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

rule 3 >>> error

In [65]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 