## Comparison

### 1. operator

In [3]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [4]:
x < 3  # less than

array([ True,  True, False, False, False])

In [5]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [6]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [7]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [8]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [9]:
x == 3  # equal

array([False, False,  True, False, False])

It is also possible to do an element-wise comparison of two arrays, and to include compound expressions:

In [10]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

#### - N-D array

In [11]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [12]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

### 2. ufunc

| Operator	    | Equivalent ufunc    || Operator	   | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``==``         |``np.equal``         ||``!=``         |``np.not_equal``     |
|``<``          |``np.less``          ||``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       ||``>=``         |``np.greater_equal`` |

### 3. Boolean Arrays 사용

In [14]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


#### - Counting entries

In [16]:
# 6보다 작은 요소 개수
np.count_nonzero(x < 6)

8

In [18]:
# 6보다 작은 요소 개수, False : 0, True : 1
np.sum(x < 6)

8

In [19]:
# 각 row에서 6보다 작은 요소 개수
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [18]:
# 8보다 큰 요소가 있는지?
np.any(x > 8)

True

In [20]:
# 0 보다 작은 요소가 있는지?
np.any(x < 0)

False

In [21]:
# 모든 요소가 10보다 작은지?
np.all(x < 10)

True

In [22]:
# 모든 요소가 6인지?
np.all(x == 6)

False

In [23]:
# 각 row의 요소가 모두 8보다 작은지?
np.all(x < 8, axis=1)

array([ True, False,  True])

### 4. Boolean operators

In [26]:
x = np.random.normal(0, 1, 1000)
np.sum((x > 0.5) & (x < 0.7))

72

In [29]:
np.sum(~( (x <= 0.5) | (x >= 0.7) ))

72

#### - operator

| Operator	    | Equivalent ufunc    || Operator	    | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``&``          |``np.bitwise_and``   ||&#124;         |``np.bitwise_or``    |
|``^``          |``np.bitwise_xor``   ||``~``          |``np.bitwise_not``   |

In [31]:
x < 0.5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False, False,  True, False, False,  True, False,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False,  True,  True,
       False,  True,  True, False, False, False,  True, False,  True,
       False, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False, False,
        True, False,

In [34]:
# 조건 선택
x[x < 0.5].shape

(711,)

In [35]:
condition = (x < 0.5)
print(np.median(x[condition]))
print(np.max(x[condition]))
print(np.min(x[condition]))
print(np.median(x[~condition]))
print(np.max(x[~condition]))
print(np.min(x[~condition]))

-0.35584821531654437
0.49917425560052553
-3.716256142266512
1.0410723428993252
3.5289173039866153
0.5007119464194904


In [36]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
print(A)
print(B)
print(A | B)

[ True False  True False  True False]
[ True  True  True False  True  True]
[ True  True  True False  True  True]


In [38]:
# error
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [41]:
# error
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()