## Fancy Indexing

In [1]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [2]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [3]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [4]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col] # X[0, 2], X[1, 1], X[2, 3]

array([ 2,  5, 11])

In [6]:
# broadcasting
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

## Combined Indexing

In [7]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
X[2, [2, 0, 1]]  # X[2,2], X[2,0], X[2,1]

array([10,  8,  9])

In [9]:
X[1:, [2, 0, 1]] # X[1,2], X[1,0], X[1,1], X[2,2], X[2,0], X[2,1], 

array([[ 6,  4,  5],
       [10,  8,  9]])

In [10]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

## Modifying Values with Fancy Indexing

In [11]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [12]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [13]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]  # x[0] = 4, x[0] = 6, 두번 변경
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1  # x[3], x[4] 값 확인
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [15]:
x = np.zeros(10)
np.add.at(x, i, 1) # x[3], x[4] 값 확인
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


## Sorting

In [16]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [17]:
x.sort()
print(x)

[1 2 3 4 5]


In [18]:
# index 반환
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [19]:
x[i]

array([1, 2, 3, 4, 5])

## Sorting along rows or columns

In [20]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [21]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [22]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Partial Sorts: Partitioning

In [23]:
x = np.array([7, 0, 4, 1, -1, 5, 100])
np.partition(x, 3) # 3번쨰 요소 기준(x.sort()후 x[3])으로 작은 것은 왼쪽, 같거나 큰것은 오른쪽

array([  0,  -1,   1,   4,   5,   7, 100])

In [24]:
np.partition(x, 4)

array([  0,  -1,   1,   4,   5,   7, 100])

In [25]:
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [26]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])